package com.swiftling.enums;

import lombok.Getter;

@Getter
public enum DefaultTag {

    NOUN("noun"),
    VERB("verb"),
    ADJECTIVE("adjective"),
    ADVERB("adverb"),
    PRONOUN("pronoun"),
    PREPOSITION("preposition"),
    CONJUNCTION("conjunction"),
    INTERJECTION("interjection"),
    ARTICLE("article"),
    DETERMINER("determiner"),
    AUXILIARY_VERB("auxiliary verb"),
    MODAL_VERB("modal verb"),
    GERUND("gerund"),
    INFINITIVE("infinitive"),
    PARTICIPLE("participle"),
    TENSE_PRESENT("tense: present"),
    TENSE_PAST("tense: past"),
    TENSE_FUTURE("tense: future"),
    TENSE_PERFECT("tense: perfect"),
    TENSE_CONTINUOUS("tense: continuous"),
    FORMAL("formal"),
    INFORMAL("informal"),
    SLANG("slang"),
    ACADEMIC("academic"),
    BUSINESS("business"),
    TRAVEL("travel"),
    RESTAURANT("restaurant"),
    SHOPPING("shopping"),
    EMERGENCY("emergency"),
    DAILY_LIFE("daily life"),
    TECHNOLOGY("technology"),
    HEALTHCARE("healthcare"),
    WEATHER("weather"),
    TRANSPORTATION("transportation"),
    SOCIAL_MEDIA("social media"),
    GREETING("greeting"),
    FAREWELL("farewell"),
    QUESTION("question"),
    ANSWER("answer"),
    REQUEST("request"),
    COMMAND("command"),
    APOLOGY("apology"),
    THANKS("thanks"),
    OPINION("opinion"),
    PERMISSION("permission"),
    ADVICE("advice"),
    WARNING("warning"),
    COMPLIMENT("compliment"),
    COMPLAINT("complaint"),
    INVITATION("invitation"),
    SUGGESTION("suggestion"),
    AGREEMENT("agreement"),
    DISAGREEMENT("disagreement"),
    FOOD("food"),
    ANIMALS("animals"),
    COLORS("colors"),
    NUMBERS("numbers"),
    TIME("time"),
    FAMILY("family"),
    CLOTHING("clothing"),
    BODY_PARTS("body parts"),
    JOBS("jobs"),
    SPORTS("sports"),
    MUSIC("music"),
    HOBBIES("hobbies"),
    SCHOOL("school"),
    NATURE("nature"),
    HOLIDAYS("holidays"),
    COUNTRIES("countries"),
    CITIES("cities"),
    BEGINNER("beginner"),
    INTERMEDIATE("intermediate"),
    ADVANCED("advanced"),
    IDIOMATIC("idiomatic"),
    COLLOCATION("collocation"),
    PHRASAL_VERB("phrasal verb"),
    PROVERB("proverb"),
    FIXED_EXPRESSION("fixed expression"),
    DECLARATIVE("declarative"),
    INTERROGATIVE("interrogative"),
    IMPERATIVE("imperative"),
    EXCLAMATORY("exclamatory"),
    SIMPLE("simple"),
    COMPOUND("compound"),
    COMPLEX("complex");

    private final String value;

    DefaultTag(String value) {
        this.value = value;
    }

}
